### ISSUE TITLE
[0;37m

### ISSUE THREAD

**Issue by seaquake** [NebbieArcane/Server#1]
Hola,
probabilmente lo sapete già, nel dubbio lo scrivo qui a futura memoria :D 

Nella schermata iniziale l'errore sulla destra è il codice colore ansi per il grigio:
http://bluesock.org/~willkg/dev/ansi.html

probabilmente ci sarà qualche typo :P 

Ovviamente non è una priorità, ma avendo fatto questa piccola ricerca, vi volevo rendere partecipi.

**Comment by francescosabatini** [comment]
Sembra che ora sia corretto, ma vorrei verificarlo sul server. Mi sono accorto che i codici ansi comportano un spostamento dell'immagine che porta a capo parte di "arcane", in tutta onesta'
stavo pensando di togliere la stradina sotto e mettere nebbie arcane a sostegno del castello, ma per
ora cominciamo a far partire la baracca e committare i typofix fatti finora.

![schermata 2018-01-14 alle 19 05 28](https://user-images.githubusercontent.com/35276719/34925290-bb22475e-f9a8-11e7-9f08-0e7fbc783e6a.png)

**Comment by seaquake** [comment]
Non mi sembrano a capo come caratteri, ma ad inizio delle rispettive righe invece che alla fine :p 
ad un primo impatto e la cosa + logica è pensare che siano a capo, ma confrontando con la e di nebbie l'ordine dei caratteri è -_) ed a me il - e _) sembrano già sulla stessa linea :D

**Comment by francescosabatini** [comment]
vero.

**Comment by seaquake** [comment]
![26907238_10215690303719320_3081263197089921183_n](https://user-images.githubusercontent.com/1249550/34966992-03979a7c-fa60-11e7-832f-6294e80b21fc.jpg)
questa immagine messa oggi da Nicola sul gruppo risulta corretta :D copiate/incollate il blocco :D
