### ISSUE TITLE
_head

### ISSUE THREAD

**Issue by seaquake** [NebbieArcane/Server#100]
Questo errore credo sia dovuto al fatto che ora il file scratch zone sia stato rinominato in _head

@alar77 qundo hai un sec se controlli plz

`  LERROR  : Fri Mar  2 12:33:14 2018 in /home/nebbie/Server/release/src/db.cpp:2319: Unable to load scratch zone file for update.`

**Comment by alar77** [comment]
In realtà è un lascito di una gestione delle zone che salvava i mob in file sotto world. Per fortuna tali file non ci sono visto che se li trovasse andrebbe ad eseguire una procedura vecchia e che fa crashare.
Tolgo messaggio e testa nella #87
