### ISSUE TITLE
TH MONO

### ISSUE THREAD

**Issue by jenesys80** [NebbieArcane/Server#107]
In merito ad una precedente discussione sul th mono, proporrei in assoluto una soluzione gia' adottata altrove e secondo me funzionale e di grande impatto. La riduzione del lag da backstab per il mono, secondo me il th mono dovrebbe stabbare e poter fuggire il round successivo. Poi non guasterebbe un moltiplicatore backstab superiore, anche di poco, ma secondo me se lo merita. Ora come ora fare il th mono, e ne ho fatto uno negli ultimi giorni, e' la classe peggiore del mud in assoluto. Poi concordo che quanto gia' discusso, che si potrebbe anche dare maggiore importanza a skill non principali come lo steal. Ma lo stab secondo me dovrebbe essere piu' veloce!
Buon lavoro!

**Comment by Mr-Carter** [comment]
Per lo steal del ladro mono abbiamo gia' pensato a qualcosa e presto lo implementeremo. Lo stab e' una questione molto complessa...zakk e scappo, zakk e scappo, zakk e scappo........che possibilità ha la vittima di sopravvivere?
