### ISSUE TITLE
TAN Possibile Bug

### ISSUE THREAD

**Issue by FoxeonNebbie** [NebbieArcane/Server#108]
In skills.c
nella funzione do_tan

Aggiunti alcuni "special" per il TAN di troll nel 2018 con un ElseIf non possibile a livello di codice
Riccorre più volte anomalia simile nei vari skin possibili.

ES: riga da 2828 a 2840 del file skills.c
                  case RACE_TROLL     :
                      if( total_bonus > 23 )
                      {
                          special = 1 ;
                          apply = APPLY_SUSC ;
                          app_val = IMM_FIRE ;
                      }
                      else if( total_bonus > 25 )
                      {
                          special = 1 ;
                          apply = APPLY_DAMROLL ;
                          app_val = 2 ;
                      }

**Comment by FoxeonNebbie** [comment]
Guardando meglio il codice l'apply è una suscettibility to fire in questo caso. Probabile che sia semplicemente errato il segno di confronto. Doveva essere un minore e non un maggiore. Tiro Basso viene la suscettibilità tiro alto ti do il bonus. Ci sono altri TAN coerenti con ciò.

**Comment by francescosabatini** [comment]
No Foxeon, il segno e' giustamente maggiore perche' il peggio che ti puo' succedere e' ottenere una comune pelle, e non una suscettibilita' che puoi sempre passare ad un mob scavanger per usarla a tuo vantaggio :P Tuttavia mi hai fatto notare che copiandomi la procedura della razza tree mi ero portato dietro un errore logico, quindi ottimo. Il fix sara' presto online.

**Comment by FoxeonNebbie** [comment]
Ok. Quindi giusto per capire toglierai l'else prima del secondo controllo è sarà solo un if >25.
Se il tiro piu i bonus da 24 da la suscettibilità mentre se fai 26 (il top of the world) becchi il piu due damroll oltre la suscettibility?
Se fai la correzione occhio perche ci sono diversi punti con questo elseif e un valore maggiore del primo controllo. Entrando nel primo non entra mai nell'else :)

**Comment by francescosabatini** [comment]
E l'ultima cosa che hai detto e' l'errore logico che ci siamo allegramente copiati a destra e a manca, ed e' risolto. Il comportamento sara' il seguente: se il total bonus e' maggiore di 25 prendi il valore piu' vantaggioso, se invece è maggiore di 23(o 24, ecc.) prendi un altro valore intermedio che puo' essere una suscettibilita' o semplicemente qualcosa di inferiore al max prize. Se non raggiungi nessuno dei casi, beh... ti attacchi.
