### ISSUE TITLE
Comando Skill per Druidi si impapocchia

### ISSUE THREAD

**Issue by FoxeonNebbie** [NebbieArcane/Server#109]
Battendo il comando skill per druidi si impapocchia l'output

Ho notato che nel srogente epr i druidi c'è una differenza 
File Act.info.cpp
Confrontare riga 4440
if (strlen(buf)+strlen(buffer) > (MAX_STRING_LENGTH*2)-2)

con riga del druido 4446
if (strlen(buf)+strlen(buffer) > MAX_STRING_LENGTH-2)

Manca per due alla lungghezza

Sotto codice druido
case 'D':
	case 'd': {
		if (!HasClass(ch, CLASS_DRUID)) {
			send_to_char("Scommetto che pensi di essere un druido.\n\r", ch);
			return;
		}
		send_to_char("La tua classe puo` imparare i seguenti spells:\n\r", ch);
		SET_BIT(ch->player.user_flags,USE_PAGING);
		for(max=0; max<IMMORTALE; max++) {
			for(i=0; *spells[i] != '\n'; i++) {
				if( spell_info[i+1].spell_pointer &&
						spell_info[i+1].min_level_druid<IMMORTALE) {
					snprintf(buf,254,"[%d] %s %s", spell_info[i+1].min_level_druid,
							 spells[i],how_good(ch->skills[i+1].learned));
					strcat(buf," \n\r"  );
					if (strlen(buf)+strlen(buffer) > MAX_STRING_LENGTH-2)
					{ break; }
					strcat(buffer, buf);
					strcat(buffer, "\r");
				}
			}
		}

**Comment by francescosabatini** [comment]
fixed, sarà up nella prossima release. min_level_druid<IMMORTALE era errato.
