### ISSUE TITLE
Eliminare uso di gdbm

### ISSUE THREAD

**Issue by alar77** [NebbieArcane/Server#11]
viene usata per conservare le "registrazioni" dei player.
Possono essere spostate su mysql

**Comment by zeflipper** [comment]
MySQL è inserito è funziona. Mi studio l’eliminazione di gdbm.

**Comment by alar77** [comment]
Considera che il codice che usa gdbm mi sono ricordato cosa fa' e perché. Forse se ci metto le mani io faccio prima?

**Comment by zeflipper** [comment]
Va bene. Io posso preparare la parte crud unificata

**Comment by alar77** [comment]
Iniziata rimozione gdnm

**Comment by alar77** [comment]
#62
