### ISSUE TITLE
Nuova Zona locanda - Apertura Porte

### ISSUE THREAD

**Issue by FoxeonNebbie** [NebbieArcane/Server#120]
Nella nuova locanda sotto la rece di myst le porte si aprono per lo piu tutte utilizzando "open 1"
Dove epr uno si puo mettere qualsiasi parola

Questo noin e un problema al primo piano sopra il bancone
Diventa pero problematico se si scende nella bisca sotto le scale che portano al piano uno.

Nella stanza della bisca c'e una secret down oltre la porta a sud da cui si arriva
Qualsiasi parola si usi apre la porta a sud
LA secret no risulta quindi apribile o trovabile

Ciao

**Comment by alar77** [comment]
Grazie, assegnato a Sea

**Comment by seaquake** [comment]
done

**Comment by FoxeonNebbie** [comment]
Satvo aggiungo che avevo trovato che era tappeto sotto il tavolino ma comunque non si apre per il bug ma aspetto che vada online la correzione :)

**Comment by seaquake** [comment]
non e' quella la parola ;) studia meglio. (cmq fix non e' ancora online in release).
