### ISSUE TITLE
Riscrivere gli script 

### ISSUE THREAD

**Issue by Mr-Carter** [NebbieArcane/Server#13]
Gli script di start devono essere rivisti ino modo che partano con i percorsi relativi.

mud_daemon
startmud
rebuild (e i relativi sottoscript in lib)

**Comment by alar77** [comment]
Prendo io io ticket perché avevo già iniziato (sbagliando) senza aprire un ticket.
mud_daemon già provvede a rilanciare il mud se cade e ho anche riattivato già i backup.
la procedura di rebuild è meno urgente perché ancora sulle aree stiamo lavorando

**Comment by alar77** [comment]
Sistemato il naming:
mud_demon -> mystd
startmud -> startmyst

**Comment by alar77** [comment]
Mud demoni e startmud già sistemato. Ora rivedo anche il building
Inviato da iPhone

**Comment by alar77** [comment]
Chiudo questo (che per riaprire il mud è sufficiente) e ne apro un altro per rimettere a posto il deploy automatico e il build delle aree
