### ISSUE TITLE
Nuova Skill Druidi - Proposta

### ISSUE THREAD

**Issue by FoxeonNebbie** [NebbieArcane/Server#133]
Ciao,
molte skill Druidiche richiedono che la stanza in cui si lanciano sia all'aperto

Creare una skill lanciabile una volta al giorno o ogni toc ore che permette di far crescere delle radice che aprono crepe nel soffitto. Di fato temporanemtne cambiano lo status della stanza da close ad aperto.
Cio permetette al druidio di usare sue spell anche al chiuso.

**Comment by francescosabatini** [comment]
Questa spell si chiama bloom, ed e' gia in calendario.
