### ISSUE TITLE
Comandi idea typo bug

### ISSUE THREAD

**Issue by Mr-Carter** [NebbieArcane/Server#16]
Controllare i comandi, secondo me sono stati disabilitati

**Comment by seaquake** [comment]
Visto che Alar si diverte ad incrociare i dati, sarebbe carina come idea che i comandi BUG ed IDEA aprissero un issue qui come i crash, il comando TYPO l'aprisse da me su gitlab (o email).

Confermo che sono disabilitati poichè ritorna il messaggio "Pardon?"

**Comment by alar77** [comment]
Buona idea, in effetti. Non velocissima da implementare (visto che chiamare le api di github dal codice del mud non è la cosa + semplice del mondo) ma certamente sarebbe utile.

**Comment by corra72** [comment]
Al momento i nuovi comandi Bug e Idea rimandano al forum.
Il comando typo manda una mail via scriba direttamente a LadyOfPain.
