### ISSUE TITLE
Nuova Skills PSI - Proposta

### ISSUE THREAD

**Issue by FoxeonNebbie** [NebbieArcane/Server#168]
1) La possibilità per gli PSI di usare la telecinesi per disarmare l'avversario.

2) La possibilità per gli PSI di prolungare la durata del Bash tenendo a terra un target gia non in piedi

3) La possibilit degli PSI di "silenziare" paralizzando le labbra del target.

**Comment by seaquake** [comment]
Ciao,
sul nuovo sito www.nebbiearcane.it c'è un forum con un apposita sezione per i suggerimenti ;)
