### ISSUE TITLE
Mettere in piedi testmud e proteggere l'accesso

### ISSUE THREAD

**Issue by Mr-Carter** [NebbieArcane/Server#17]
Il discorso e' che se abbiamo un testmud sempre online, i players potrebbero utilizzarlo per esplorare, il che impedirebbe loro di perdere l'eq nelle dt o quando sono vaporizzati dai boss.

Ci sono vari sistemi: 

1) preautenticazione
2) deletare tutti i pg, non consentire la registrazione, e lasciare 4-5 pg a cui cambiamo la pass, da assegnare ai tester per un tempo limitato.

Come facciamo?

**Comment by alar77** [comment]
Ci era sfuggita la soluzione piu' semplice:
gira sulla 4001 (che è firewallata)
per accedere, basta aprirsi un tunnell ssh e si possono usare anche i client.
L'ho attivato.
