### ISSUE TITLE
Procedura di deploy del codice e delle aree

### ISSUE THREAD

**Issue by alar77** [NebbieArcane/Server#19]
A me piacerebbe come idea, che pushare su certi branch (test e release) mandasse rispettivamente online il codice e le aree relative sul mud di test o sul mud di prod.
Usiamo questo ticket per ragionarci.
Un tool che ho visto usare è https://github.com/frinknet/GitPushy

**Comment by seaquake** [comment]
ricordati che aree ora sono divise per cartelle, non ho idea se la procedura che le trasforma in un megafile le digerisca in quel modo :D

**Comment by alar77** [comment]
No, se non non avrei scritto che devo rivederla :)

**Comment by alar77** [comment]
Completato, vedi https://ci.nebbie.it
