### ISSUE TITLE
Bug Skill Imparate da multiclasse con il So non castasbili con cast

### ISSUE THREAD

**Issue by FoxeonNebbie** [NebbieArcane/Server#191]
Se si impara una skill sia come sorcio che come cleric non risulta piu castabile dal cleric ma va recallata

Questo può capitare anche con Dispell Magic
Ovviamente un multiclasse che deve recallare i dispell risulta meno efficace di uno che dispella di mana cleric.
La discriminante e se per errore lo pracchi sorcio.

Il bug è in questo controllo
File: spell_parserc
Function: void do_cast(struct char_data* ch, const char* ori_argument, int cmd) {

	/* this should make sorcerer learned spells be forced to be recalled */
	if( (cmd == CMD_CAST || cmd == CMD_MIND) && HasClass(ch,CLASS_SORCERER) &&
			!IS_IMMORTAL(ch) && IS_SET(ch->skills[spl].flags,SKILL_KNOWN_SORCERER) ) {
		send_to_char("Questo e` un incantesimo da stregone...\n\r",ch);
		return;
	}

E necessario inserire un altro controllo per verificare se la skill è learned come Cleric oltre che come sorcerer e quindi non uscire dalla funzione

Ciao
MA

**Comment by alar77** [comment]
> La discriminante e se per errore lo pracchi sorcio.
Ehm, quindi non è un bug. sei tu che hai sbagliato a praccare :)
Si suppone che se pracchi da sorcio sia una scelta (che ha effetti benefici, ad esempio puoi lanciare la spell quando sei senza mana).
Non sono molto convinto di modificarlo, magari c'è chi conta sul fatto di usare tutto il mana per curare ma avere sempre a disposizione il dispel

**Comment by FoxeonNebbie** [comment]
Secondo me uno dovrebbe poterlo castare da so o da CL.
Cosi invece avendolo praccato anche da sorcio non posso piu usarlo da cleric.
Non ho modo di tornare indietro
Se voglio il dispel clerci con mana devo rirollare. non posso tornare indietro neanche perdendo le prac...
Mi sembra un po un trappola...

**Comment by FoxeonNebbie** [comment]
Si potrebbe valutare alla peggio di implementare un comando che permetta di fare unlearn al costo di due sessione e disimparare la skill.

**Comment by alar77** [comment]
Perché? E' costruzione del personaggio. Nella tua crescita per le spell presenti in entrambe le classi fai una scelta che dipende dal tuo modo di giocare. Eventualmente si potrebbe valutare un "unprac" che costa una prac e ti consente di disimparare una spell se l'hai imparata sulla classe sbagliata

**Comment by FoxeonNebbie** [comment]
Nel mio caso ho un triclasse gia parzialmente trainato in cui ho palesemente cannato.
Preferirei potere usare dispel con entrambe le modalita ovviamente. Quella è ovviamente scelta di chi implementa il mud se renderlo possibile o far scegliere. Per quanto riguarda il mio caso sepcifico volendo praccare prima del 19 ho prccato dispel da clerico senon erro e poi avendo molte skill accumulate dovendo praccare qualcosa ho dato la ditata su prac disp dal sorcio. si attiva il flag anche se non ce l'avevi ad excell ma l'avevi parzialmente inziaiata cleric e ormai sei fregato... Personaggio "Etere"

**Comment by wizardmorgan** [comment]
Mi fanno notare che se pracchi entrambe vanno tutte e due su anche se ne usi solo una. Comunque potrebbe essere costruzione del pg se fosse consapevole. In realtà questa “feature” non credo sia esplicita, no? L’unica alternativa è farsi wippare a morte :D

**Comment by FoxeonNebbie** [comment]
Praccato Str non me lo fa piu praccare CL... Appena riprovato nel dubbio. E il codice allegato alla segnalazione mi sembra proprio non contenere controlli per il dopio prac. Semplicemente se l'hai imparata da Stregone allora non puoi usare comando cast.
