### ISSUE TITLE
Investigare Razza Demone

### ISSUE THREAD

**Issue by francescosabatini** [NebbieArcane/Server#30]
E' la piu' integrata con il mud a livello di codice, e favorisce i caster. Penso andrebbe implementata visto che in game sembra molto stabile.

**Comment by zeflipper** [comment]
Parto con la code review, inseriamo una "natural armor" per il demone, che in fondo anche attr ti da "Corazzato come un demone". Valutiamo però, se non già presente, ma lo saprò solo dopo la code review, se (io dico si) inserire anche qualche sfighetta.

**Comment by zeflipper** [comment]
Attualmente sono state implementate le seguenti feature:

1. Leech: si tratta di un'abilità di razza, non va praccata. Nel momento in cui il demone infligge danno (sia da spell che fisico), risucchia energia vitale all'avversario secondo la seguente formula

```
int modWis = wis_app[(int)GET_RWIS(ch)].bonus;
int randNumb = number(0,GetMaxLevel(ch));
int leech = MIN((modWis + randNumb)/4, dam);
```
2. Immolate: ha funzionamento simile al cannibalize dello psi e permette di convertire hp in mana. Va praccato da un mob con la special "DemonTeacher" e per ora costa 1*GetMaxLevel(ch) coins + una sessione di pratica. Ha spellfail. A riposo converte 1:1 hp e mana. In combat la metà.

Chiacchierando, per dare più giocabilità alla classe mu e per trovare un bilanciamento che possa permettere anche a mu mono di avere appeal, si pensava di:

1. Leech: passare da /4 a /2 per aumentare il numero di hp risucchiabili, ma limitandolo al danno fisico
2. Immolate: dopo il livello 30, trasformare la conversione in 2:1 a riposo e 1:1 in combat.

**Comment by zeflipper** [comment]
Rilasciata su master in attesa delle aree.
