### ISSUE TITLE
Sysmess: (LIMITS)Sto cazzone maxxa la classe 2 a 14799

### ISSUE THREAD

**Issue by seaquake** [NebbieArcane/Server#32]
circa alle 11:39 del 22/01/2018
Per curiosità, sto sottile messaggio cosa indica? :D

**Comment by alar77** [comment]
Non è mia, io di solito scrivo inglese, ci dovro' guardare

**Comment by Mr-Carter** [comment]
mi pare ci fosse un bug sugli xp nell'era che fu . probabilmente fu messo per controllare.
