### ISSUE TITLE
Hai Fame. Hai sete.

### ISSUE THREAD

**Issue by seaquake** [NebbieArcane/Server#33]
Palrliamone... :D 

Se vi rollate un pg livello 1, praticamente state sempre morti di fame e di sete, fino ad arrivare al "sei esausto". Non ricordo in passato, forse sono vecchio... ma veramente è richiesta continua.

Sono rimasto + di una volta bloccato con Panoramix esausto in giro :D fortuna che mi son venuti a salvare :P 

Non ho idea se è stato toccato qualcosa a livello di tick o simili in passato, ma imho allungare un po' i tempi non sarebbe male.

Se passate a guardare la procedura, correggete anche "Hai Fame." in "Hai fame."  ;)

**Comment by alar77** [comment]
Disabilitato l'effetto fame sete sotto l livello 5
3.2.x #62
