### ISSUE TITLE
Editor Aree

### ISSUE THREAD

**Issue by seaquake** [NebbieArcane/Server#41]
Ho bisogno di sapere con quale editor effettuare le modifiche.

Sia Eleutheria che EleiEditor (MUDEditor) sono entrambi configurati per Nebbie.

Il quesito che vi pongo nasce dal fatto che entrambi effettuano delle modifiche di formattazione del testo all'interno dei file.

Vi allego ( [Accademia_TEST.zip](https://github.com/NebbieArcane/Server/files/1667650/Accademia_TEST.zip) ) l'area Accademia (vnum 7800-7899) in 3 versioni:

- Originale: File passati da Nick, con correzione typo e fix manuale issue 8 (gitlab); solo notepad++.

- Eleutheria: Typo (notepad++) + Fix con Eleutheria.

- EleiEditor: Typo (notepad++) + Fix con EleiEditor.

Con una semplice comparazione vedrete che ad esempio il .wld ha diversi cambiamenti di formattazione al suo interno.

Se mi dite che al codice non interessa nulla di tutto cio' ma si basa semplicemente sulle ~ sarebbe un passo avanti.

Mi fido di Elei, è molto preciso, ma se gentilmente le buttate su una macchina di test e vedete se generano errori. Non mi interessano errori estetici, semplicemente che sia up l'area ed al codice piaccia :D

**Comment by seaquake** [comment]
P.s. scusate se ve rompo, ma vorrei evitare di lavorare diverso tempo per poi scoprire che il lavoro è da rifare :P

**Comment by alar77** [comment]
Sono ragionevolmente sicuro che il codice si basa esclusivamente sui ~.
Il crash del PC mi ha notevolmente incasinato col lavoro, ma spero nel fine settimana di poter sistemare il load delle aree e quindi iniziare a mettere su test il tuo lavoro (per il quale intanto ti ringrazio visto che mi sa che ancora non l'aveva fatto nessuno)

**Comment by seaquake** [comment]
Potervi aiutare è un enorme piacere, rivedere up Nebbie mi fa tornare felice come un bimbo :D 

E' solo merito vostro il poterci ritrovare nuovamente tutti insieme a ridere e scherzare con i soliti bei flame!  ❤️
