### ISSUE TITLE
Typo nel value

### ISSUE THREAD

**Issue by seaquake** [NebbieArcane/Server#43]
Darkangel sudia lo Stocco del Baluardo Bianco intensamente.

**Comment by zeflipper** [comment]
Magari mettere anche il comando e qualche informazione in più? :-)

**Comment by seaquake** [comment]
il comando è value era nell'oggetto :P ed il typo è sTudia invece di sudia

Non saprei che altro aggiungere :p

**Comment by seaquake** [comment]
risolto o chiuso nel mucchio? lol
