### ISSUE TITLE
Fix cap per train dello straccione

### ISSUE THREAD

**Issue by francescosabatini** [NebbieArcane/Server#44]
Come per i principi deve essere fatto un check che impedisce allo straccione di far credito.

file spec_procs2.c line 7194

**Comment by Mr-Carter** [comment]
non solo, vanno riviste anche le soglie. Praticamente va rivisto tutto perche' se non permettiamo ai pg di andare in negativo, il costo non sarà mai pagabile. Se abbassiamo le soglie, con pochissimi xp si arriva a 18. 

Potremmo permetterlo solo se hai ALMENO un certo livello (cioe' un certo numero di xp), il che consentirebbe di fare solo 1 prac alla volta. Per questo dobbiamo considerare che molti vogliono praccare COS il prima possibile, per non essere penalizzati nel gain degli HP

**Comment by alar77** [comment]
Mi devo fare un'idea a modo per questo.
Anche perché ero abbastanza contrario :)
(Thanatos aveva 208 punti vita ed è stato il primo immortale per meriti
di gioco, e che cazzo)


Il 02/02/2018 19:32, Mr-Carter ha scritto:

**Comment by seaquake** [comment]
a parte che l'andare in "negativo" alla fine faceva parte del gioco, perchè rende molto piu' facile morire e droppare il livello.
