### ISSUE TITLE
Variabile genere

### ISSUE THREAD

**Issue by seaquake** [NebbieArcane/Server#45]
C'era una variabile da usare nelle descrizioni di stanze, mob ed oggetti che automaticamente cambiava  la parola in base al genere del personaggio.

Mi pare fosse $b

esempio:
Ti senti impaurit$b 
per i maschi: Ti senti impaurito
per le femmine: Ti senti impaurita

semplicemente differenziava unicamente a ed o.

Confermate? ne conoscete altre? **grin**

**Comment by seaquake** [comment]
Ok, ovviamente come ho scritto a voi l'ho ritrovata.

Confermo $b per il genere maschile femminile.

$p ripropone il nome dell'oggetto
$n nome del pg che legge.

Le ho trovate su oggetto vnum 2010

**Comment by seaquake** [comment]
@zeflipper mi sai dire quando funziona? ho provato a metterlo in una desc di una room ma non funziona

**Comment by alar77** [comment]
Viene interpretato direi solo da act e actall, ovvero le routine che descrivono ai personaggi cosa succede.
Non mi pare proprio che le descrizioni siano parsate (e fra l'altro non avrebbe senso, la room è statica. La scrivi una volta per tutte, non è che la descrizione cambia a seconda di chi c'è nella stanza)

**Comment by seaquake** [comment]
ok, grazie
