### ISSUE TITLE
Rivedere la procedura di calcolo del rent al boot

### ISSUE THREAD

**Issue by Mr-Carter** [NebbieArcane/Server#5]
In passato il comando store faceva rentare il pg con un rent di 0 coin. Quando termina il periodo di store, non esiste una procedura che ricalcola il rent e lo applica al pg. Morale: storo per 2 settimane e se non torno piu' non pago mai piu' il rent.

**Comment by seaquake** [comment]
non ho afferrato, ma se pago zero di store/rent perchè dovrei pagare al rientro?

o intendi che una volta usato lo store a zero coin, in futuro anche se prendo oggetti che rentano 100000 coin pagherei sempre zero? Perchè in questo secondo casa sappiamo qual è la procedura corretta da seguire **grin**

**Comment by alar77** [comment]
Non al rientro, ma dal giorno successivo a quello in cui scade lo store.
Lo store si aspettava player onesti, che usassero store perché ne avevano bisogno.
Quindi azzera il costo di rent "fino al successivo rent". 
Se uno non rientra mai, non pagherà mai + nulla.
La procedura corretta avrebbe dovuto essere "scrivo fino a che data non paghi rent (perché hai pagato in anticipo) e quando è passata ricominci a pagare normale"

**Comment by seaquake** [comment]
Nuke! :D

**Comment by seaquake** [comment]
L'idea che avevo suggerito, per un ritorno soft dei vecchi, era di lasciare una settimana di tempo per riloggare i vecchi pg (con lo store disattivato). Chi non viene loggato durante questi 7 giorni, viene denudato dalla procedura di Flyp (inattività) :D

**Comment by Mr-Carter** [comment]
lo store fino al fix, resta disattivato
