### ISSUE TITLE
comando world

### ISSUE THREAD

**Issue by Mr-Carter** [NebbieArcane/Server#54]
L'orario di partenza e' errato. Serve correggerlo per sistemare un'altra issue (cd del dust devil).

Isildur (T) *|*-Vs-*|*world
Base Source: AlarMUD Versione 3.2.1-1-g876a335 Release 97.
Compilazione del : Feb  4 2018 00:42:55.
Orario di partenza: Thu Jan  1 00:00:00 1970 
Orario attuale    : Mon Feb  5 09:11:08 2018 
Indice di attesa: 243067 usec
Indice medio   : 243059 usec

**Comment by alar77** [comment]
Fixed 3.2.x
