### ISSUE TITLE
cooldown dust devil e reboot

### ISSUE THREAD

**Issue by Mr-Carter** [NebbieArcane/Server#55]
La spell ha 24 h di CD.
Se casto dust devil 1 minuto prima del reboot,  dopo il reboot mi ritrovo con il cd e senza devil.

Se fixiamo il time del server (vedi comando world) possiamo mettere un check in fase di cast che controlla se il cd e' iniziato prima di un reboot o meno, per fare override al cooldown e permettere il cast e il reset del cd.

**Comment by zeflipper** [comment]
mifate la lista delle spell con cooldown che vanno trattate come il dust devil, please?

**Comment by francescosabatini** [comment]
Fire servant, earth servant, wind servant, fire servant, dust devil, find familiar
