### ISSUE TITLE
leech demone

### ISSUE THREAD

**Issue by Mr-Carter** [NebbieArcane/Server#57]
Propongo una miglioria del calcolo degli hp che tornano al player dal leech.

Oggi la formula si basa sul danno, su una stat e su un modificatore random; questo non permette di darlo a molte classi (il wa ad esempio si curerebbe troppo).

Propongo di modificare la formula e di fare in modo che:

- lasciare la formula attuale facendo in modo che il max ottenibile sia piu' basso (orientativamente a 5 o meno). Deve tenere conto del livello. Vedi esempio.
- inserire un moltiplicatore adatto alla classe. Ogni classe avrà il suo. Vedi esempio
- inserire un divisore in caso di pg multiclasse. Vedi esempio

Esempio:
max leech per hit: 5 (tarate la formula.....)
moltiplicatori: Mu 3x ; Th 2x; Wa 1x
Divisori:  biclasse divide per 3, triclasse da decidere

Simulazione:
5 leech per hit diventano:
mu: 15 hp (22 max per round il mu al 50 ha 1,5 attacchi)
th:10 hp (15 max per round th al 50 ha 1,5 attacchi)
wa: 5hp (20 max per wa ha 3,5; questa monoclasse non la permetteremo al demone in ogni caso.)
mu/th: (15+10)/3 = 9 (13 max media round)
mu/wa: (15+5)/3= 6 (18 max media round)

**Comment by zeflipper** [comment]
A me viene un solo dubbio: il leech ha senso in combo con l'immolation, altrimenti è solo sgravo e basta.
Io, molto più radicalmente, lo darei solo ai mu mono/multiclasse, ma non agli altri.

**Comment by seaquake** [comment]
imho solo un mu pazzo userebbe immolation in combat.
Dovrebbe essere una situazione tragicomica, ovvero finisce il mana, il combat va avanti, ed ha molti hp (quindi probabilmente il mob sta missando a nastro) e quindi usa immolation per continuare.

Invece i 22hp a round al 50 al mu mono... bho non voglio renderlo immortale, ma mi sembrano pochini. 
Stesso concetto, se sta tankando (altrimenti sarebbe full hp e chissene se li usa per avere + mana) 22 hp non so nulla per un mu gracilino.

Se invece la vediamo in combo con immolation per stare sempre full mana, da supporter. ok nessun problema, anzi anche troppi.

**Comment by Mr-Carter** [comment]
facciamo delle simulazioni e vediamo se 5/hit e' giusto oppure dobbiamo abbassarlo di qualche decimale.
L'approsimazione deve essere a livello di INT (cioe' sempre per difetto, si prende solo la parte intera della formula)
