### ISSUE TITLE
Prac immolation 

### ISSUE THREAD

**Issue by Mr-Carter** [NebbieArcane/Server#58]
1) prac immolation non fa il controllo delle prac. l'ho praccata con un pg appena creato che non aveva prac session da spendere. con 4 prac sono arrivato a superbo.

2) c'e' un check gold coin. Attualmente ogni prac costa 1 moneta. O lo rivediamo o lo leviamo, 1 coin per prac non ha senso

**Comment by seaquake** [comment]
se si fa "prac mu" lontano dai maestri, immolation non è elencata nelle lista delle spell praccate

**Comment by alar77** [comment]
Ovviamente. Ci sono altre abilità razziai? Come si comporta oracolo per quelle?

Inviato da iPhone
