### ISSUE TITLE
Blast psi (da foxeon)

### ISSUE THREAD

**Issue by alar77** [NebbieArcane/Server#61]
File skills.c
Function void do_blast( struct char_data *ch, char *argument, int cmd)
Righe 5708 - 5711
if( ( potency < 14 ) && ( number( 1, 50) < GetMaxLevel( victim ) ) )
potency-- ;
if( ( potency < 15 ) && ( number( 1, 52) < GetMaxLevel( victim ) ) )
potency -= 2 ;

Il check della potenza 15 (potenza che sembra non essere raggiungibile per i mortali) finisce per applicarsi sempre oltre quello della 14.
Il risultato e che ai livelli bassi se va di sfiga toglie tre livelli di potenza al blast (check 14 -1 potenza e check 15 -2 potenza) .

Forse il check era voluto per principi o altro ma non c'è il limite con la potenza > 14?

Grazie per la verifica

**Comment by FoxeonNebbie** [comment]
Pnesate ai poveri PSI con l'epistassi che blastano sbucciando solo le ginocchia :)
