### ISSUE TITLE
Area Editor

### ISSUE THREAD

**Issue by seaquake** [NebbieArcane/Server#67]
Un po' di idee che mi frullano per la testa in merito, non prendetela come una todo list ma come spunto di riflessione:

- Iniziamo con il classico import/export dei file (che imho non dovrebbe mai mancare perchè spesso ravanare di notepad++ viene piu' facile, ad es. con le traduzioni) per poi passare a qualche automatismo tipo che quando lo apri pulla master, crea una branch in cui quando il builder salva, fa il commit e push a fine sessione?
- Utilizzo. Dovrebbe esserci una login (anche l'universale github visto che state uniformando), e dei livelli di utilizzo. Tipo uno senza permessi non accede a nulla; primo livello (builder) può lavorare in un'area a lui assegnata e vedere solo il suo lavoro; secondo livello (editor) può revisionare lavoro builder; terzo livello (capo builder).
- Caricare le aree contemporaneamente ed un bel campo cerca (vnum o descrizione).
- Valori consigliati. Elei nel suo editor, ha inserito questa particolarità. Come già sottolineato non sono per uniformare tutti i mob ad un algoritmo, ma soprattutto per i builder alle prime armi, e cmq per tutti come punto di riferimento l'idea è molto carina.
- Oggetti 5° valore. File zon negli altri editor lo chiama "room limit", probabilmente in Nebbie questo quinto valore se presente non fa considerare al count del boot gli oggetti rentati. Creando così la categoria oggetti maxxanti in-game. Dico probabilmente poichè siamo arrivati a questa conclusione paragonando oggetti in game con e senza., la certezza la potete dare solo voi coder.
```
O <if-flag> <obj vnum> <max existing> <room vnum> 0
```

**Comment by alar77** [comment]
Ottimo. Adesso da bravo fai copia e incolla e lo metti nel repoository giusto :)
