### ISSUE TITLE
No Knock in structs.hpp

### ISSUE THREAD

**Issue by seaquake** [NebbieArcane/Server#68]
Nel file structs.hpp alla linea 678 tra le opzioni delle direzioni manca il bitvector 512 che gli editor assegnano al no knock

Pertanto quando viene utilizzato all'init dell'area si ha:
`Sysmess: Door error - zone 43, cmd 128, loc 5242 (fixed) in Old Thalos`

```
#5242
I bagni turchi~
Qui  erano  i  bagni  comuni della citta'. Vapore d'acqua esce da
alcuni  buchi  del  pavimento  mentre  da  uno  squarcio  si vede
dell'acqua  bollente  scorrere  sotto  il pavimento. In un angolo
dello  squarcio  aperto si e' incastrato il cadavere di una donna
(forse...)  ormai  irriconoscibile.  Verso ovest si vede un'altra
casa crollata. ~
33 8 1
D0
~
~
0 0 5243 -1
D3
The wall has collapsed on the adjoining house, creating a new opening
in it.~
~
0 0 5244 -1
D5
E'  strano...molto  strano! L'acqua che scorre non penetra dentro
il  buco ma prosegue tranquillamente per la sua direzione bagnando
la morta all'altezza delle spalle.~
morta~
8|16|32|256|512 0 5252 224
E
cadavere donna~
Riesci a vedere chiaramente solo testa anche se ti sembra che il
corpo sia ancora intatto. Esso e' incastrato in posizione eretta,
ci deve essere un buco o una fossa sotto ai piedi di questa donna. ~
S
```

In particolare questa linea è differente da circlemud:
`8|16|32|256|512 0 5252 224`

8|16|32|256|512 abbiamo visto cosa sono

0 vuol dire uscita diretta (niente chiave)
5252 room di destinazione
224  pull, invece del normale open/close.

Ricapitolando imho l'errore dovrebbe scaturire dal bitvector mancante.

**Comment by alar77** [comment]
Se manca vuol dire che non è implementato. 

Inviato da iPhone
