### ISSUE TITLE
#Drunk

### ISSUE THREAD

**Issue by seaquake** [NebbieArcane/Server#99]
Questo è roba vostra...

`  LERROR  : Fri Mar  2 05:32:57 2018 in /home/nebbie/Server/release/src/db.cpp:4234: Unable to open script "#Drunk" for reading.`

**Comment by zeflipper** [comment]
Nelle lib c'è un file che si chiama script.dat. Dovrebbero essere una sorta di "speciali" che vengono assegnati a mob con quel vnum. Nella cartella script, infatti, ci sono file con un elenco di comandi che fanno parlare, muoversi, fare emote ai suddetti mob.

#Drunk 3064
ZepGuy 3606
RobMin 11036
Mime 3075
Dog 16106
Banker 3078
Seneca 3047

Immagino che qualcuno pensasse che mettendo l'hash a Drunk, commentasse quella riga, stoppando lo script, invece così facendo il codice cerca il file #Drunk, che ovviamente non trova e logga l'errore.
Si risolve o ripristinandolo correttamente, o cancellando la riga.

**Comment by seaquake** [comment]
e cmq i mob 3075 e 3078 non esistono

**Comment by zeflipper** [comment]
la correzione è da fare sul file, roba da builder

**Comment by seaquake** [comment]
@zeflipper nei file .spe dei builder non c'e' nessun riferimento a #Drunk o al mob 3064.
